<?php
/**
 * Module Name: API Global Styles CSS
 * Description: This module adds a REST API endpoint for fetching the CSS styles generated by WP core's Global Styles system.
 * Namespace: ApiGlobalStylesCss
 *
 * @package fse-studio
 */

declare(strict_types=1);

namespace FseStudio\ApiGlobalStylesCss;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Register the API routes.
 */
function register_routes() {
	$version   = '1';
	$namespace = 'fsestudio/v' . $version;
	register_rest_route(
		$namespace,
		'/get-global-styles-css',
		array(
			array(
				'methods'             => 'GET',
				'callback'            => __NAMESPACE__ . '\get_global_styles_css',
				'permission_callback' => __NAMESPACE__ . '\get_global_styles_permission_check',
				'args'                => get_request_args(),
			),
			'schema' => 'response_item_schema',
		)
	);
}

/**
 * Get the rendered CSS for a specific theme json file.
 *
 * @param WP_REST_Request $request Full data about the request.
 * @return WP_Error|WP_REST_Request
 */
function get_global_styles_css( $request ) {
	$params = $request->get_params();

	$module_dir_path = dirname( module_dir_path( __FILE__ ) ) . '/theme-json-data-handlers/';

	$styles = wp_get_global_styles( $module_dir_path . '/theme-json-files/' . $params['name'] . '.json' );

	if ( ! $styles ) {
		return new \WP_REST_Response(
			array(
				'error' => 'There was a problem getting the global styles css',
			),
			200
		);
	} else {
		return new \WP_REST_Response( $styles, 200 );
	}
}

/**
 * Check the permissions required to take this action.
 *
 * @param WP_REST_Request $request Full data about the request.
 * @return WP_Error|bool
 */
function get_global_styles_permission_check( $request ) {
	return true;
}

/**
 * Required args for a get request.
 *
 * @return array
 */
function get_request_args() {
	$return_args = array(
		'name' => array(
			'required'          => true,
			'type'              => 'string',
			'description'       => __( 'The filename of the theme.json file', 'fse-studio' ),
			'validate_callback' => __NAMESPACE__ . '\validate_arg_is_string',
			'sanitize_callback' => 'sanitize_text_field',
		),
	);

	return $return_args;
}

/**
 * Validation callback for simple string parameters.
 *
 * @param mixed           $value   Value of the the parameter.
 * @param WP_REST_Request $request Current request object.
 * @param string          $param   The name of the parameter.
 */
function validate_arg_is_string( $value, $request, $param ) {
	$attributes = $request->get_attributes();

	if ( isset( $attributes['args'][ $param ] ) ) {
		$argument = $attributes['args'][ $param ];
		// Check to make sure our argument is a string.

		if ( 'string' === $argument['type'] && ! is_string( $value ) ) {
			// Translators: 1: The name of the paramater in question. 2: The required variable type.
			return new WP_Error( 'rest_invalid_param', sprintf( esc_html__( '%1$s is not of type %2$s', 'fse-studio' ), $param, 'string' ), array( 'status' => 400 ) );
		}
	} else {
		// Translators: The name of the paramater which was passed, but not registered.
		return new WP_Error( 'rest_invalid_param', sprintf( esc_html__( '%s was not registered as a request argument.', 'fse-studio' ), $param ), array( 'status' => 400 ) );
	}

	// If we got this far then the data is valid.
	return true;
}


/**
 * Validation callback for simple string parameters.
 *
 * @param mixed           $value   Value of the the parameter.
 * @param WP_REST_Request $request Current request object.
 * @param string          $param   The name of the parameter.
 */
function validate_arg_is_object( $value, $request, $param ) {
	// TODO: add logic that validates the object is what we expect.
	return true;
}

/**
 * Initialize the REST route.
 *
 * @since 1.0.0
 * @return void
 */
function instantiate_rest_api_routes() {
	register_routes();
}
add_action( 'rest_api_init', __NAMESPACE__ . '\instantiate_rest_api_routes', 11 );

/**
 * Retrieves the item's schema, conforming to JSON Schema.
 * The properties value is what you can expect to see in a successful return/response from this endpoint.
 *
 * @since 1.0.0
 *
 * @return array Item schema data.
 */
function response_item_schema() {
	return array(
		// This tells the spec of JSON Schema we are using which is draft 4.
		'$schema'    => 'https://json-schema.org/draft-04/schema#',
		// The title property marks the identity of the resource.
		'title'      => 'get_theme',
		'type'       => 'object',

		// These define the items which will actually be returned by the endpoint.
		'properties' => array(
			'themejsonData' => array(
				'description' => esc_html__( 'The themejson data in question', 'fse-studio' ),
				'type'        => 'string',
				'readonly'    => true,
			),
		),
	);
}
